CREATE TABLE IF NOT EXISTS users (
  id                     VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  name                   VARCHAR(150)  NOT NULL,
  email                  VARCHAR(255)  NOT NULL UNIQUE,
  cpf                    VARCHAR(14)   NOT NULL UNIQUE COMMENT 'Formato: 000.000.000-00',
  phone                  VARCHAR(20)   NULL,
  password_hash          VARCHAR(255)  NOT NULL,
  role                   ENUM('pai','mãe','responsável legal','avô','avó','outro') NOT NULL DEFAULT 'pai',
  custody_type           ENUM('compartilhada','unilateral','alternada','sem definição formal') NULL,
  avatar_url             VARCHAR(500)  NULL,
  email_verified_at      DATETIME      NULL,
  email_verify_token     VARCHAR(64)   NULL,
  reset_token            VARCHAR(64)   NULL,
  reset_token_expires_at DATETIME      NULL,
  low_conflict_mode      TINYINT(1)    NOT NULL DEFAULT 0,
  is_active              TINYINT(1)    NOT NULL DEFAULT 1,
  lgpd_version           VARCHAR(10)   NOT NULL DEFAULT '1.2',
  created_at             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at             DATETIME      NULL,
  PRIMARY KEY (id),
  INDEX idx_email (email),
  INDEX idx_cpf (cpf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
