CREATE TABLE IF NOT EXISTS events (
  id                     VARCHAR(36)  NOT NULL DEFAULT (UUID()),
  connection_id          VARCHAR(36)  NOT NULL,
  child_id               VARCHAR(36)  NOT NULL,
  created_by_user_id     VARCHAR(36)  NOT NULL,
  title                  VARCHAR(200) NOT NULL,
  description            TEXT         NULL,
  location               VARCHAR(300) NULL,
  category               ENUM('escola','saúde','lazer','guarda','outros') NOT NULL,
  event_date             DATE         NOT NULL,
  start_time             TIME         NULL,
  end_time               TIME         NULL,
  recurrence             ENUM('none','daily','weekly','biweekly','monthly') NOT NULL DEFAULT 'none',
  recurrence_end_date    DATE         NULL,
  status                 ENUM('pending','confirmed','conflict','cancelled') NOT NULL DEFAULT 'pending',
  confirmed_by_creator   TINYINT(1)   NOT NULL DEFAULT 1,
  confirmed_by_coparent  TINYINT(1)   NOT NULL DEFAULT 0,
  parent_event_id        VARCHAR(36)  NULL,
  created_at             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at             DATETIME     NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (connection_id) REFERENCES coparent_connections(id),
  FOREIGN KEY (child_id) REFERENCES children(id),
  FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  INDEX idx_event_date (event_date),
  INDEX idx_connection_events (connection_id, event_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
