CREATE TABLE IF NOT EXISTS expenses (
  id                          VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  connection_id               VARCHAR(36)   NOT NULL,
  child_id                    VARCHAR(36)   NOT NULL,
  submitted_by_id             VARCHAR(36)   NOT NULL,
  title                       VARCHAR(200)  NOT NULL,
  description                 TEXT          NULL,
  category                    ENUM('saúde','educação','lazer','vestuário','outros') NOT NULL,
  amount                      DECIMAL(10,2) NOT NULL,
  split_ratio                 ENUM('50/50','70/30','30/70','100/0','0/100') NOT NULL DEFAULT '50/50',
  status                      ENUM('pending','approved','contested','paid','cancelled') NOT NULL DEFAULT 'pending',
  receipt_minio_key           VARCHAR(500)  NULL,
  receipt_name                VARCHAR(255)  NULL,
  contest_reason              TEXT          NULL,
  contested_by_id             VARCHAR(36)   NULL,
  contested_at                DATETIME      NULL,
  approved_at                 DATETIME      NULL,
  paid_at                     DATETIME      NULL,
  payment_method              ENUM('pix','transferencia','dinheiro','outro') NULL,
  payment_receipt_minio_key   VARCHAR(500)  NULL,
  expense_date                DATE          NOT NULL,
  created_at                  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at                  DATETIME      NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (connection_id)   REFERENCES coparent_connections(id),
  FOREIGN KEY (child_id)        REFERENCES children(id),
  FOREIGN KEY (submitted_by_id) REFERENCES users(id),
  FOREIGN KEY (contested_by_id) REFERENCES users(id),
  INDEX idx_connection_expenses (connection_id, status),
  INDEX idx_expense_date (expense_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
