CREATE TABLE IF NOT EXISTS support_agreements (
  id                  VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  connection_id       VARCHAR(36)   NOT NULL,
  payer_id            VARCHAR(36)   NOT NULL,
  payee_id            VARCHAR(36)   NOT NULL,
  payment_mode        ENUM('desconto_em_folha','pix','transferencia','deposito','dinheiro','in_natura','misto') NOT NULL,
  due_day             TINYINT       NOT NULL DEFAULT 5,
  readjustment_mode   ENUM('valor_fixo','percentual_salario_minimo') NOT NULL DEFAULT 'valor_fixo',
  readjustment_index  VARCHAR(20)   NULL,
  legal_basis         ENUM('acordo_extrajudicial','sentenca','acordo_judicial','sem_titulo') NOT NULL DEFAULT 'acordo_extrajudicial',
  legal_doc_minio_key VARCHAR(500)  NULL,
  start_date          DATE          NOT NULL,
  end_date            DATE          NULL,
  notes               TEXT          NULL,
  status              ENUM('ativo','suspenso','encerrado') NOT NULL DEFAULT 'ativo',
  created_by_id       VARCHAR(36)   NOT NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at          DATETIME      NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (connection_id) REFERENCES coparent_connections(id),
  FOREIGN KEY (payer_id)      REFERENCES users(id),
  FOREIGN KEY (payee_id)      REFERENCES users(id),
  FOREIGN KEY (created_by_id) REFERENCES users(id),
  INDEX idx_conn_status (connection_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_agreement_items (
  id              VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  agreement_id    VARCHAR(36)   NOT NULL,
  child_id        VARCHAR(36)   NULL,
  base_value      DECIMAL(10,2) NOT NULL,
  min_wage_factor DECIMAL(6,3)  NULL,
  is_active       TINYINT(1)    NOT NULL DEFAULT 1,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (agreement_id) REFERENCES support_agreements(id),
  FOREIGN KEY (child_id)     REFERENCES children(id),
  INDEX idx_agreement (agreement_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_installments (
  id              VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  agreement_id    VARCHAR(36)   NOT NULL,
  connection_id   VARCHAR(36)   NOT NULL,
  reference_month CHAR(7)       NOT NULL,
  due_date        DATE          NOT NULL,
  amount_due      DECIMAL(10,2) NOT NULL,
  amount_paid     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status          ENUM('pendente','pago','pago_parcial','atrasado','contestado','dispensado') NOT NULL DEFAULT 'pendente',
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_agreement_month (agreement_id, reference_month),
  FOREIGN KEY (agreement_id)  REFERENCES support_agreements(id),
  FOREIGN KEY (connection_id) REFERENCES coparent_connections(id),
  INDEX idx_conn_status (connection_id, status),
  INDEX idx_due (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_payments (
  id                  VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  installment_id      VARCHAR(36)   NOT NULL,
  connection_id       VARCHAR(36)   NOT NULL,
  paid_by_id          VARCHAR(36)   NOT NULL,
  amount              DECIMAL(10,2) NOT NULL,
  payment_mode        ENUM('desconto_em_folha','pix','transferencia','deposito','dinheiro','in_natura','misto') NOT NULL,
  paid_at             DATETIME      NOT NULL,
  receipt_minio_key   VARCHAR(500)  NULL,
  receipt_name        VARCHAR(255)  NULL,
  kind                ENUM('pagamento','estorno') NOT NULL DEFAULT 'pagamento',
  reverses_payment_id VARCHAR(36)   NULL,
  confirmation_status ENUM('aguardando','confirmado','contestado') NOT NULL DEFAULT 'aguardando',
  confirmed_by_id     VARCHAR(36)   NULL,
  confirmed_at        DATETIME      NULL,
  contest_reason      TEXT          NULL,
  notes               TEXT          NULL,
  hash                CHAR(64)      NOT NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (installment_id)  REFERENCES support_installments(id),
  FOREIGN KEY (connection_id)   REFERENCES coparent_connections(id),
  FOREIGN KEY (paid_by_id)      REFERENCES users(id),
  INDEX idx_installment (installment_id),
  INDEX idx_conn (connection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
